=== Stephan-Schneider/shiftplan/src/main/resources/shiftplan.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="shiftplan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="public-holidays">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="holidays">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="holiday" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" use="optional" type="xs:string"/>
                                                <xs:attribute name="date" use="required" type="xs:date"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="year" type="xs:int" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="employee-groups">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="employee-group" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="groupname" type="xs:string" />
                                        <xs:element name="employees">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="employee" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="name" type="xs:string" />
                                                                <xs:element name="lastname" type="xs:string" />
                                                                <xs:element name="lateshift-only" type="xs:boolean" />
                                                                <xs:element name="lateshift-order" default="-1" type="xs:int" />
                                                                <xs:element name="color" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Stephan-Schneider/shiftplan/src/main/resources/shiftplan.xml
<?xml version="1.0" encoding="UTF-8" ?>

<shiftplan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="shiftplan.xsd" for="2023" start-date="2023-04-01" end-date="2023-05-31">
    <public-holidays>
        <holiday name="Neujahr" date="2023-01-01"/>
        <holiday name="Karfreitag" date="2023-04-07"/>
        <holiday name="Ostermontag" date="2023-04-10"/>
        <holiday name="Tag der Arbeit" date="2023-05-01"/>
        <holiday name="Christi Himmelfahrt" date="2023-05-18"/>
        <holiday name="Pfingstmontag" date="2023-05-29"/>
        <holiday name="Fronleichnam" date="2023-06-08"/>
        <holiday name="Tag der dt. Einheit" date="2023-10-03"/>
        <holiday name="Heiligabend" date="2023-12-24"/>
        <holiday name="1. Weihnachtstag" date="2023-12-25"/>
        <holiday name="2. Weihnachtstag" date="2023-12-26"/>
        <holiday name="Sylvester" date="2023-12-31"/>
    </public-holidays>
    <shift-duration>
        <home-office>2</home-office>
        <max-late-shift>5</max-late-shift> <!-- Die tats채chliche Anzahl von Sp채tschichten kann in Abh채ngigkeit vom Homeoffice-Plan abweichen -->
    </shift-duration>
    <employee-groups>
        <employee-group>
            <group-name>Gruppe A</group-name>
            <employees>
                <employee>
                    <name>Greta</name>
                    <lastname>Th체nberg</lastname>
                    <lateshift-only>false</lateshift-only>
                    <lateshift-order>5</lateshift-order>
                    <color>#336699</color>
                    <ooo>
                        <absence start="2023-05-02" end="2023-05-05"/>
                        <absence start="2023-06-12" end="2023-06-23"/>
                    </ooo>
                </employee>
                <employee>
                    <name>Luisa</name>
                    <lastname>Neubauer</lastname>
                    <lateshift-only>true</lateshift-only>
                    <lateshift-order>2</lateshift-order>
                    <color>#ff0000</color>
                </employee>
            </employees>
        </employee-group>
        <employee-group>
            <group-name>Gruppe B</group-name>
            <employees>
                <employee>
                    <name>Alexander</name>
                    <lastname>Gauland</lastname>
                    <lateshift-only>true</lateshift-only>
                    <lateshift-order>4</lateshift-order>
                </employee>
                <employee>
                    <name>Beatrix</name>
                    <lastname>von Storch</lastname>
                    <lateshift-only>false</lateshift-only>
                    <lateshift-order>1</lateshift-order>
                </employee>
            </employees>
        </employee-group>
        <employee-group>
            <group-name>Gruppe C</group-name>
            <employees>
                <employee>
                    <name>Donald</name>
                    <lastname>Trump</lastname>
                    <lateshift-only>false</lateshift-only>
                    <lateshift-order>3</lateshift-order>
                </employee>
                <employee>
                    <name>Silvio</name>
                    <lastname>Berlusconi</lastname>
                    <lateshift-only>false</lateshift-only>
                    <lateshift-order>0</lateshift-order>
                    <color>#ff00aa</color>
                </employee>
            </employees>
        </employee-group>
    </employee-groups>
</shiftplan>
